# Generated by Django 3.2.5 on 2021-07-31 09:23

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to=account.models.upload_user_pic, validators=[account.models.validate_image_size], verbose_name='Profile picture'),
        ),
    ]
