# Generated by Django 3.2.5 on 2021-07-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
